### ISSUE TITLE
Kavorka dependency is problematic

### ISSUE THREAD

**Issue by eserte** [Csson/p5-Map-Metro#10]
There are at least two problems with Kavorka:
* it depends on Parse::Keyword, which is marked as deprecated (see https://rt.cpan.org/Ticket/Display.html?id=102318 )
* it depends on Devel::CallChecker, which does not build on Windows systems (see https://rt.cpan.org/Ticket/Display.html?id=103830 )

The latter means that any Map::Metro plugin cannot be installed cleanly on Windows systems.

**Comment by Csson** [comment]
Hi,

I didn't know about those, but I have planned to remove the Moops/Kavorka dependencies for various reasons. Might be a while before it is done, but it is on my todo list.

**Comment by Csson** [comment]
This was done in 0.2400.
