### ISSUE TITLE
t/basic.t fails (with Moose 2.1802)

### ISSUE THREAD

**Issue by eserte** [Csson/p5-Map-Metro#12]
A sample fail report with the failing test: http://www.cpantesters.org/cpan/report/04f6edd4-2332-11e6-a917-5b3d2ec07716

Statistical analysis thinks that the problem is caused by the newest Moose (@moose FYI):
http://analysis.cpantesters.org/solved?distv=Map-Metro-0.2404

**Comment by Csson** [comment]
Bumped Moose requirement in 0.2405 (to 2.1803).
